---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
  - "**/node_modules"
